import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#4CAF50',
  primaryLight: '#a5d6a7',
  background: '#f5f5f5',
  white: '#white',
  danger: '#f44336',
  text: '#666',
  disabled: '#999',
  border: '#ddd',
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 40,
    position: 'relative',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: colors.text,
  },
  form: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginBottom: 16,
    backgroundColor: colors.background,
    paddingHorizontal: 10,
  },
  inputIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
    tintColor: colors.primary,
  },
  inputWithIcon: {
    flex: 1,
    padding: 12,
    fontSize: 16,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  buttonDisabled: {
    backgroundColor: colors.primaryLight,
  },
  buttonIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
    tintColor: 'white',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
  },
  linkContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  linkText: {
    color: colors.primary,
    textAlign: 'center',
    fontSize: 16,
  },
  otpContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'white',
  },
  otpInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 8,
    marginVertical: 30,
    width: '100%',
    paddingHorizontal: 15,
  },
  otpIcon: {
    width: 24,
    height: 24,
    marginRight: 10,
    tintColor: colors.primary,
  },
  otpInput: {
    flex: 1,
    padding: 15,
    fontSize: 24,
    textAlign: 'center',
    letterSpacing: 10,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  timerIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
    tintColor: colors.text,
  },
  timer: {
    fontSize: 18,
    color: colors.text,
  },
  resendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  resendIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    tintColor: colors.primary,
  },
  disabledIcon: {
    tintColor: colors.disabled,
  },
  disabledText: {
    color: colors.disabled,
  },
  logoutContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoutIcon: {
    width: 18,
    height: 18,
    marginRight: 5,
    tintColor: colors.danger,
  },
  logoutText: {
    color: colors.danger,
    fontSize: 16,
  },
  otpButton: {
    backgroundColor: '#2196F3',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  otpButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  emailText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 10,
    marginBottom: 20,
    textAlign: 'center',
  },
  backContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
  },
  backIcon: {
    width: 16,
    height: 16,
    marginRight: 5,
    tintColor: colors.text,
  },
  backToLoginText: {
    color: colors.text,
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  logo: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  smallLogo: {
    width: 50,
    height: 50,
    marginBottom: 15,
  },
  eyeIconContainer: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eyeIcon: {
    width: 22,
    height: 22,
    tintColor: colors.text,
  },
  switchingContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 300,
  },
  switchingText: {
    marginTop: 15,
    fontSize: 16,
    color: colors.primary,
    fontWeight: '500',
  },
});